### ISSUE TITLE
Add support for mass evolving by waiting and use Lycky Egg to boost XP.

### ISSUE THREAD

**Issue by halvors** [PocketMobsters/PokeMobBot#357]
Add support for mass evolving by waiting and use Lycky Egg to boost XP.

**Comment by torin555** [comment]
Uh... The bot already has this.

**Comment by halvors** [comment]
How? I don't se any information about this in the console nor config.

**Comment by kaeld59** [comment]
Have a lucky egg in the bag, config is:

  "UseLuckyEggsWhileEvolving": true,
  "UseLuckyEggsMinPokemonAmount": 30,

but still doesn't wait for the 30 evolve to use the lucky egg

**Comment by AngelKillzIt** [comment]
doesnt work if you dont have keep mindupepokemon set to 1 , and keep pokemon to evolve at set to true it still transfers them might be a bug but mass evolving doesnt work right now least unless you buy lots of pokemon space and keep supes set alot higher

**Comment by halvors** [comment]
And there is no informational message in the console either.

**Comment by torin555** [comment]
It works fine for me. Turn on the setting to keep all evolvable pokemon.

**Comment by halvors** [comment]
Do i need to turn off this one?

"EvolveAllPokemonWithEnoughCandy": true

**Comment by torin555** [comment]
Nope

**Comment by vapp13** [comment]
I have: 
  "KeepMinDuplicatePokemon": 1,
  "EvolveAllPokemonWithEnoughCandy": true,
  "UseLuckyEggsWhileEvolving": true,
  "UseLuckyEggsMinPokemonAmount": 70,
  "KeepPokemonsThatCanEvolve": true,

For me is working like charm. I think you're missing the last one. Quote from the wiki " When PokeMobBot determines how many Pokemon to transfer due to duplicates, it will create a count based on the number of candies the account has for that species compared to the number required to evolve. For example, if the account has 5 Pidgeys (12 candies to evolve) and 24 candies, PokeMobBot will keep the top two Pidgeys and transfer the rest"

**Comment by vapp13** [comment]
On console you'll see something like this: "[09:13:42] Not enough Pokemon to trigger a lucky egg. Waiting for 47 more. (23/70)"

**Comment by AngelKillzIt** [comment]
I have all those set like that not working transfers all doesn't save up the 30 and transfer the rest

**Comment by vapp13** [comment]
I forgot to said that  "EvolveAllPokemonWithEnoughCandy" works together with  "PokemonsToEvolve" list. So those 30 (Or 70 in my case) will count within the pokemons on your PokemonsToEvolve list, all rest are ignored even if you have enough candies.

**Comment by AngelKillzIt** [comment]
I left that on true but not working

**Comment by Valmere** [comment]
Open a new issue if the problem persists after the next release
