### ISSUE TITLE
Too frequent inventory management

### ISSUE THREAD

**Issue by vfuyong** [PocketMobsters/PokeMobBot#37]
It can happen a few times in 10 seconds. Please make the frequency adjustable through config file.

**Comment by littlemonster1** [comment]
this seems to work fine every 5 Pokestops when not using GPXpathing:

"If UseGPXPathing is set to true and GPXFile is found, Evolution, updating, transferring, recycling and sniping will execute every second or based on the value in milliseconds for MinDelayBetweenSnipes (whichever is higher)."

When using GPXPathing however, the inventory management happens very often as vfuyong mentioned.
Apparently MinDelayBetweenSnipes is not taken into account since the number I used is a lot higher than every few seconds.

A fix so that we can use GPXPathing would be greatly appreciated.

**Comment by lorilith** [comment]
according to the following:
`_lastTasksCall =
                                DateTime.Now.AddMilliseconds(Math.Min(session.LogicSettings.DelayBetweenPlayerActions,
                                    3000));`

it looks as though it is checking for 3 seconds or Delay between actions, whichever is smallest
