### ISSUE TITLE
"KeepPokemonsThatCanEvolve" doesn't work for Nidoran

### ISSUE THREAD

**Issue by Xe1** [PocketMobsters/PokeMobBot#380]
My "KeepMinDuplicatePokemon" is set to 2 and it always transfers the 3rd Nidoran(f) it catches even though I have 400+ candies.

**Comment by vapp13** [comment]
Remember that "KeepPokemonsThatCanEvolve" works together with the "PokemonsToEvolve" list. You'll need to add Nidoran to the list.

**Comment by guay0ta** [comment]
I don't get your problem. If the value is set to 2 it's normal to transfer the third?

**Comment by vapp13** [comment]
@Xe1 have a look here for a better understanding of how evolving works #357 (I just explained it to another guy ;) )

**Comment by Xe1** [comment]
I'm sorry I wasn't clear enough. I'm talking about "KeepPokemonsThatCanEvolve". As explained in the Wiki:

"For example, if the account has 5 Pidgeys (12 candies to evolve) and 24 candies, PokeMobBot will keep the top two Pidgeys and transfer the rest."

It works perfectly for other pokemon. Right now it's keeping 30 Pidgeys because I have 360 Pidgey candies, and the same thing for my Weedles and Caterpies. But for Nidoran it ignores that entirely and transfers only based on the "KeepMinDuplicatePokemon" value.

**Comment by vapp13** [comment]
Make sure you add Nidoran to the evolve list. For example:
"PokemonsToEvolve": [
    "caterpie",
    "weedle",
    "pidgey",
    "rattata",
    "spearow",
    "zubat",
    "drowzee",
    "doduo",
    "nidoran"

**Comment by Xe1** [comment]
I don't want to EVOLVE nidoran, I just want to KEEP them based on the candy amount. Right now the bot is KEEPING 30 pidgeys and 20 weedles because I have enough candy to evolve them all, but it's not doing that for nidoran. I don't want the bot to evolve anything.

**Comment by littlemonster1** [comment]
@Xe1 you probably have Pidgey on that list and it does not evolve either ...

as long as you have evolve when enough candy off it will not evolve but according to vapp13 - unless you put nidoran on that list it will not keep it since it does not consider nidoran a pokemon you might want to evolve. So if you have evolving off and keep pokemon that can evolve on as well as them added to the list you should be fine ...

**Comment by Xe1** [comment]
@littlemonster1 Thanks, I'll try that.

@vapp13 I tried adding Nidoran but the bot crashes on start. Do I need to specify the gender somehow? I tried Nidoran♀ but it crashes too.

**Comment by vapp13** [comment]
Well, that's a good question, how the bot difference between the Nidoran♂ and Nidoran♀. Actually I don't know.
The error must be caused by a missing ","Make sure there's a "," after every argument like this  "caterpie", "weedle", "pidgey", "rattata", "spearow", "zubat", "drowzee", "doduo", "nidoran".

Maybe you added nidoran at last but forgot to add the "," after the previous argument. If nidorian is your last pokemon on the list before the square bracket "]," you don't need to add the ",".

You will need to test the bot adding the male and female symbols to see if the bot recognize the different. I hope this help!

**Comment by Xe1** [comment]
@vapp13 NidoranFemale worked, and this solved my original problem. Thank you for all your help.
