### ISSUE TITLE
razz berry not thrown?

### ISSUE THREAD

**Issue by ryuugana** [PocketMobsters/PokeMobBot#488]
Are razz berries not being thrown?
http://prntscr.com/c0w0na

http://prntscr.com/c0w1vg

http://prntscr.com/c0w37o

**Comment by littlemonster1** [comment]
IF you are using current release, they are not thrown away. Will be fixed with next release. However, you can go into your config and set e.g. "UseBerryBelowCatchProbability": 0.4, or even higher and it should use berries quite and fix your issue for now.
To be safe (since I did not check the code) maybe set UseBerryMinCp and UseBerryMinIv low too.

**Comment by ryuugana** [comment]
Ok, thank you.
