### ISSUE TITLE
Pokesnipelocationserver

### ISSUE THREAD

**Issue by rbusk7** [PocketMobsters/PokeMobBot#503]
no "usesnipeonlinelocationserver", only "usesnipelocationserver" and "usepokesnipelocationserver". not sure if that makes a difference, but even then i tried setting both to true (not at the same time) and they never attempted to go to the location, ran like i had it set to false. have it set to snipe every 60 seconds and never did after 5 min of running

**Comment by jjskuld** [comment]
Pokesniper server sniping is currently broken due to cloudflare ddos protection being enabled.

**Comment by chopraaa** [comment]
@jjskuld These are 2 different settings.

`  "UseSnipeLocationServer": true,
  "UsePokeSnipersLocationServer": false,`

#470 is also unrelated to the SnipeLocationServer issue. This issue is related to the LocationFeeder applications. The LocationFeeder sends the co-ordinates to the bot but the bot doesn't snipe those Pokemon.

**Comment by chopraaa** [comment]
Problem can be fixed by deleting `config.json`. @rbusk7 

Issue can be closed.

**Comment by jjskuld** [comment]
@chopraaa Yes I am aware of the differences.
Use
```"UseSnipeLocationServer": true``` if you want to use the Location Feeder.  Currently there is an issue where the LocationFeeder does not send correct expiration times.  Since the bot currently checks that the expiration time is valid, the majority of the pokemon will not be sniped.

```"UsePokeSnipersLocationServer": true``` if you want to attempt sniping from Pokesnipers.com.  Currently broken due to Cloudflare DDOS protection.

And yes, you are right, #470 was a fix for "manual" sniping from fixed list of coordinates.

**Comment by Valmere** [comment]
Closing as it was an issue with the previous release and #470 has been merged.
