### ISSUE TITLE
How about using Nox with a bot?

### ISSUE THREAD

**Issue by steffo78** [PocketMobsters/PokeMobBot#579]
Would it be possible to write a bot that actually uses the screen to farm pokestops and catch pokemon?

I have read something about pixel recognition, so that a bot is able to recognize for example a pokestop. So if we run pokemon go in an emulator like Nox it should use the screen output. And as Nox has implemented WASD for moving around, the bot should actually move pretty easy by itself.

I think the biggest problem is catching pokemon and reading the stats. I know it is easy to make a macro for throwing pokeballs, but can the bot actually identify a pokemon when it's on the screen?

At least you wouldn't have to worry of the API changing.

But I'm probably fantasying about the impossible, but you never know what some of you guys are able of :D

**Comment by jinkawasaki333** [comment]
What would someone need that?

**Comment by L4T3-D4Z3** [comment]
Thought about this option a long time ago. Assuredly it would be possible but in my opinion way too ornate.

**Comment by jinkawasaki333** [comment]
Well, it is not impossible by using SikuliX, but Nox is pretty laggy and I don't see there is a point to use graphic recognition bot.

**Comment by pokemongofan** [comment]
agreed

**Comment by mcjoshmcjosh** [comment]
There is a point because Niantic could update the API with every update to make it harder to bot. If there was a color scraping bot, that wouldn't be an issue meaning the bot would be more stable and require updates less frequently. However, the people working on adjusting their bots to the new API know more about whether or not that's worth the effort. It may very well be easier to just fix the bot to be compatible with server updates.

**Comment by Nothingst** [comment]
So right now the API has been changed? No bots we can use right?

**Comment by mcjoshmcjosh** [comment]
I'm not sure if there any that have been updated to work with the new API, but it doesn't seem very likely. I'm just going to wait for PokeMobBot to be updated because the devs were on the issue immediately after it surfaced, so I imagine they will have an update before or at the same time as other bots.

**Comment by Valmere** [comment]
not explicitly related to PokeMobBot, closing.
