### ISSUE TITLE
Question about recent pokestop value changes

### ISSUE THREAD

**Issue by Guardiandota** [PocketMobsters/PokeMobBot#593]
Okay so we know that pokestop values changed, but my bot does not say that no pokestops available, it just displays egg status (which is not changing), and no pokemons are detected at all. So the console log consists of egg status repeating with same distance left.

Maybe there is something more than just pokestop value changes? Any info about that?

**Comment by jay691337** [comment]
This has been posted a million times, take a look before you leave your comment.

**Comment by Guardiandota** [comment]
https://www.reddit.com/r/pokemongobotting/comments/4w0n29/cannot_find_poketops/
It seems that major changes were made to the way clients communicate with the API. It'll take us a little while to reverse engineer it and implement a fix. In the meanwhile, i suggest taking those OP accounts you botted up to now and try them on gyms. We'll keep updating this channel as more information comes. We have no ETA for now. A reminder that any trolling about bans or hate on the devs for no reason will result in removal from the server.Thank you for your patience and support!

**Comment by UraharaKisuke07** [comment]
Are you suggesting a solution to yourself?

**Comment by strids89** [comment]
Just in the meantime, Download nox or gym battle. The more post you make asking about how long it will take the longer it will take for them to get it done.

**Comment by Niro007** [comment]
I constantly see the same questions over and over and i do not complain at all.. i can here to seek for help and to learn. There's nothing wrong about asking a question, maybe the person doesn't know how to look it up or just wants a quick answer, if people ask me then i would answer otherwise i would just move along but i've been seeing these rude comments about repeated questions.
Remember we are here to learn not to get lectured... Gracias.

Ponganse las pilas!

**Comment by UraharaKisuke07** [comment]
@Niro007 the problem with that is more and more people will continue asking the same question over and over and the front page will be full of them.  
If they just want a quick answer and can't be bothered with scrolling just a bit down the page which is titled "Issues", then yes, there's a lot wrong with it. 
Also you're doing the same thing you were advising against. ie. not moving along, lecturing etc when you posted that paragraph. 
Also if nobody corrects them, then how are they supposed to learn?

**Comment by Niro007** [comment]
Nop i'm not doing the same i got my point across and said what i wanted because of how you guys are handling things (treat people the way you want to be treated it goes a long way regardless of the question) but who am i to say that right? Keep doing what you want i'm not the one that looks bad here.

Ponganse las pilas!

**Comment by UraharaKisuke07** [comment]
Fine. Let's keep making duplicate posts until they solve the issue and not point them in the right direction. That'll teach them. 
You are our lord and saviour and we are the wretched ones.

**Comment by Niro007** [comment]
What ever.. the truth hurts.

**Comment by UraharaKisuke07** [comment]
It does, doesn't it?

**Comment by feedbuck** [comment]
Where will the fix be posted at?

**Comment by Valmere** [comment]
Updates on the current situation can be found in the #announcements channel in discord
