### ISSUE TITLE
Transfer pokemon logic

### ISSUE THREAD

**Issue by qwer4790** [PocketMobsters/PokeMobBot#67]
"KeepMinCp": 0,
 "KeepMinDuplicatePokemon": 30,
 "KeepMinIvPercentage": 90.0,
 "KeepPokemonsThatCanEvolve": false,
 "TransferDuplicatePokemon": true,

I set it like this, and I remove everything in  "PokemonsTransferFilter": {},

It doesn't transfer anything and full my inventory very soon.
How to set it to make it transfer any pokemon that below 90% iv?

**Comment by FatSacks** [comment]
If you read the wiki it explains all these. RTFM. Google it.

KeepMinCP: 0 means you're keeping any pokemon with a **minimum CP of 0** - so every pokemon
KeepMinDuplicatePokemon : 30 means you are keeping a **minimum of 30** pokemon of each type - so **at least 30 pokemon** of any type with min CP 0
KeepMinIVPercentage : 90 means keep any pokemon who has an IV value of **90% or greater**
TransferDuplicatePokemon: true means let the bot transfer any pokemon who doesn't satisfy the above criteria.

So you want:
KeepMinCP: Any high value because you really only want high IV pokemon because IV can't be changed. So setting high CP (like 1500) means all pokemon below 1500 are flagged for transfer
KeepMinDuplicatePokemon: Set this to a low value like 1-3 will force the bot to **keep at a minimum 1-3** pokemon of any type
KeepMinIVPercentage: 90 so any pokemon below 90% are flagged for transfer
TransferDuplicatePokemon: true

**Comment by qwer4790** [comment]
I fuxked up understanding the logic, so it's "and" not "or", thank you for explaining it
